### ISSUE TITLE
Criar CRUDs para cadastro de pedidos

### ISSUE THREAD

**Issue by rastapf** [DHSC05G04/candySphere#46]
Cadastro de pedidos deve ser feito utilizando dados diretamente do BD (ao invés do JSON atual)

1. Criação de Seeds
- [x] Terminais
- [x] Caixas
- [x] Status
- [x] Formas de pagamento
- [x] Pedidos
- [x] Comandas
- [x] Recebimentos

2. Validação dos models
- [x] Terminais
- [x] Caixas
- [x] Status
- [x] Formas de pagamento
- [x] Pedidos
- [x] Comandas
- [x] Recebimentos

3. Criação das rotas / controllers para cada entidade como API
- [x] Terminais
- [x] Caixas
- [x] Status
- [x] Formas de pagamento
- [x] Pedidos
- [x] Comandas
- [x] Recebimentos

**Comment by asovitorio** [comment]
> Cadastro de pedidos deve ser feito usando dados diretamente do BD (ao usar o JSON atual)
> 
> 1. Criação de Sementes
> 
> * [x]  Terminais
> * [x]  Caixas
> * [x]  Status
> * [x]  Formas de pagamento
> * [x]  Pedidos
> * [x]  Comandas
> * [x]  Recebimentos
> 
> 1. Validação dos modelos
> 
> * [x]  Terminais
> * [x]  Caixas
> * [x]  Status
> * [x]  Formas de pagamento
> * [x]  Pedidos
> * [x]  Comandas
> * [x]  Recebimentos
> 
> 1. Criação de rotas / controladores para cada entidade como API
> 
> * [x]  Terminais
> * [x]  Caixas
> * [x]  Status
> * [x]  Formas de pagamento
> * [x]  Pedidos
> * [x]  Comandas
> * [x]  Recebimentos

**Comment by asovitorio** [comment]
Concluido
